### ISSUE TITLE
Custom keyboard shortcuts are not working in macOS Mojave

### ISSUE THREAD

**Issue by LitoFrame** [teras/Jubler#17] opened 2020-05-04 17:17 UTC
Hello, in macOS 10.14.6 in the 7.0.0 version the custom keyboard shortcuts are not working. 
I can create custom shortcuts in system preferences which are visible in the menu of Jubler, but they don't work. They are working in version 6.
Thanks!

**Comment by teras** [comment] 2020-05-06 00:14
I tested it and it works.
It seems that some shortcuts are not accepted, I couldn't find an obvious pattern.

One of the changes between version 6 and 7 is the migration to Java 11, which was a required step and probably Java 11 broke some things.

Another thing I noticed is, [Cmd]+[key] works all the time, while [Ctrl]+[key] not all combinations.

**Comment by LitoFrame** [comment] 2020-05-06 14:04
I use custom shortcuts for Tools-->Shift time and Tools-->Recode menu items, but none of my variations work. My custom shortcuts in version 6 was cmd+shift+T and cmd+shift+R, I tried literally every combinations in version 7 without success. I also tried to create shortcuts for other menu items, but they failed to work as well.
When I push the keyboard I can see the Tools menu (or other menu for different items) "flashes", but nothing happen.
The original keyboard shortcuts are working fine.

**Comment by teras** [comment] 2020-05-22 08:55
Can you check this release?
https://github.com/teras/Jubler/releases/tag/v7.0.1-beta
I have updated to latest JRE, just in case...

**Comment by LitoFrame** [comment] 2020-05-22 09:14
Unfortunately it is not working.

**Comment by teras** [comment] 2020-05-22 09:16
The problem is right now I can't reproduce your problem. Two weeks ago I was able to break a couple of keystrokes but can't any more.

Can you try to reset all shortcuts and start anew and see if the problem still persists?

**Comment by LitoFrame** [comment] 2020-05-22 09:22
I deleted all my shortcuts and created again, but the problem still persists.

**Comment by teras** [comment] 2020-05-22 09:38
Is this for all shortcuts? 
Maybe tell me your full software specifications to see if we can find something.

**Comment by LitoFrame** [comment] 2020-05-22 09:45
I have custom shortcuts for all applications, Safari, Maps, Pages, Numbers, iTunes, BBedit and Jubler. All shortcuts are working, except Jubler.
What do you mean my full software specification?

**Comment by teras** [comment] 2020-05-22 09:46
Which version of OS, and anything that could help me reproduce the problem.
How do you change shortcuts? From inside Jubler or from System Preferences?

**Comment by LitoFrame** [comment] 2020-05-22 09:56
macOS 10.14.6, I tried it on my iMac (Retina 5K, 27-inch, 2017) and my MacBook Pro (Retina, Mid 2012)
I created the shortcuts through System Preferences.
I didn't know I can do it in Jubler. :) Now I tried it and it is working. So the problem is between System Preferences and Jubler.

**Comment by teras** [comment] 2020-05-22 09:59
So, using Jubler's method, it did work, right?

**Comment by LitoFrame** [comment] 2020-05-22 10:02
Yes, it is.

**Comment by teras** [comment] 2020-05-22 10:03
OK then I'll close this issue.

**Closed by teras** 2020-05-22 10:03 UTC
Labels: bug

**Comment by LitoFrame** [comment] 2020-05-22 10:32
OK, thanks for your support!
